import { HashMap } from "./hash.js";

let test = new HashMap();

test.set('1', 'maroon');
test.set('2', 'lime');
test.set('3', 'teal');
test.set('4', 'navy');
test.set('5', 'cyan');
test.set('6', 'olive');
test.set('7', 'coral');
test.set('8', 'plum');
test.set('9', 'peach');
test.set('10', 'mint');
test.set('11', 'rose');
test.set('12', 'cream');
test.set('13', 'charcoal');
test.set('14', 'bronze');
test.set('15', 'ruby');
test.set('16', 'emerald');
test.set('17', 'sapphire');
test.set('18', 'jade');
test.set('19', 'amber');
test.set('20', 'topaz');
test.set('21', 'ivory');
test.set('22', 'pearl');
test.set('23', 'gold');
test.set('24', 'silver');
test.set('25', 'lavender');
test.set('26', 'orchid');
test.set('27', 'mustard');
test.set('28', 'blush');
test.set('29', 'tan');
test.set('30', 'sand');
test.set('31', 'auburn');
test.set('32', 'mahogany');
test.set('33', 'periwinkle');
test.set('34', 'turquoise');
test.set('35', 'mulberry');
test.set('36', 'indigo');
test.set('37', 'amethyst');
test.set('38', 'onyx');
test.set('39', 'obsidian');
test.set('40', 'garnet');
test.set('41', 'citrine');
test.set('42', 'malachite');
test.set('43', 'opal');
test.set('44', 'moonstone');
test.set('45', 'basil');
test.set('46', 'hazel');
test.set('47', 'sage');
test.set('48', 'buttercup');
test.set('49', 'sunflower');
test.set('50', 'cherry');
test.set('51', 'raspberry');
test.set('52', 'blueberry');
test.set('53', 'cranberry');
test.set('54', 'pine');
test.set('55', 'spruce');
test.set('56', 'moss');
test.set('57', 'ash');
test.set('58', 'graphite');
test.set('59', 'smoke');
test.set('60', 'dust');
test.set('61', 'cloud');
test.set('62', 'fog');
test.set('63', 'ice');
test.set('64', 'snow');


console.log(test.entries());